title: Welcome!
author: mateuscoelho
email: mateuscoelho2009@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Mateus's Portfolio Page

# social links
twitter_username: your-twitter-handle
github_username:  mateuscoelho2009

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
